spark:
    image: apache/spark:3.5.0
    container_name: spark
    user: root
    depends_on:
      - kafka
    environment:
      - SPARK_MODE=master
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark-apps/gcp-key.json
    volumes:
      - ./spark:/opt/spark-apps
      - ~/.config/gcloud/application_default_credentials.json:/opt/spark-apps/gcp-key.json
    command: >
      bash -c "mkdir -p /home/spark/.ivy2/cache &&
      chmod -R 777 /home/spark/.ivy2 &&
      /opt/spark/bin/spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.36.1
      /opt/spark-apps/spark_stream.py"